// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRhR8FBkPTBDuan3jeGDlKzoTTcpbfeFA',
    appId: '1:281777917189:web:8bfd2de3b5dbf6458a3b6c',
    messagingSenderId: '281777917189',
    projectId: 'coba-ab414',
    authDomain: 'coba-ab414.firebaseapp.com',
    storageBucket: 'coba-ab414.firebasestorage.app',
    measurementId: 'G-WWP02C0CX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4og-7GnZsVklumcKFPk9i1oKtmKl2heY',
    appId: '1:281777917189:android:e7eca79bf59bac5a8a3b6c',
    messagingSenderId: '281777917189',
    projectId: 'coba-ab414',
    storageBucket: 'coba-ab414.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiWzg8gDTOSxRmnNH8Ld2OGvm8WJv-AhM',
    appId: '1:281777917189:ios:4db8343874b4d2408a3b6c',
    messagingSenderId: '281777917189',
    projectId: 'coba-ab414',
    storageBucket: 'coba-ab414.firebasestorage.app',
    iosBundleId: 'com.example.coba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiWzg8gDTOSxRmnNH8Ld2OGvm8WJv-AhM',
    appId: '1:281777917189:ios:4db8343874b4d2408a3b6c',
    messagingSenderId: '281777917189',
    projectId: 'coba-ab414',
    storageBucket: 'coba-ab414.firebasestorage.app',
    iosBundleId: 'com.example.coba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRhR8FBkPTBDuan3jeGDlKzoTTcpbfeFA',
    appId: '1:281777917189:web:f84a849d5c12c4e38a3b6c',
    messagingSenderId: '281777917189',
    projectId: 'coba-ab414',
    authDomain: 'coba-ab414.firebaseapp.com',
    storageBucket: 'coba-ab414.firebasestorage.app',
    measurementId: 'G-6DYKKJHTZT',
  );
}
